version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node-fetch"
    versions:
    - 2.5.9
  - dependency-name: "@types/node"
    versions:
    - 14.14.37
  - dependency-name: vsce
    versions:
    - 1.87.0
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.1
  - dependency-name: "@types/vscode"
    versions:
    - 1.54.0
